### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by Mato-Z** [zecure/shadowd_ui#2] opened 2015-09-07 09:18 UTC
Hello,

I have installed shadowd_ui on Debian 7 x64, according to https://shadowd.zecure.org/overview/user_interface/ and it was analogically as on Debian 8 x64. But until all on Debian 8 is ok, here I have this problem:

When I run web interface in webbrowser I get this error message:

Compile Error: Can't use method return value in write context in /var/www/shadowd_ui/src/Swd/AnalyzerBundle/Controller/ProfileController.php line 190 

Logs:
EMERGENCY - Can't use method return value in write context
CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Can't use method return value in write context in /var/www/shadowd_ui/src/Swd/AnalyzerBundle/Controller/ProfileController.php line 190" at /var/www/shadowd_ui/src/Swd/AnalyzerBundle/Controller/ProfileController.php line 190 

Many thanks for help.

**Comment by zit-hb** [comment] 2015-09-07 15:21
Hey Mato,

thanks for reporting the problem. This is caused by `empty($profile->getKey())`, because in old PHP versions empty only supported variables as input. I had a similar bug prior to this (#0a2a33d), but I missed this one. It is fixed now though in Github (#a0d38d7) and a patched + signed version on the file server will be released in some hours.

**Closed by zit-hb** 2015-09-07 15:21 UTC

**Comment by Mato-Z** [comment] 2015-09-07 21:49
@zit-hb Thanks for help again!
